---
- name: Enable the RPM Fusion repositories (free and nonfree)
  become: yes
  dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    disable_gpg_check: yes
    state: present

- name: Install core packages
  become: yes
  dnf:
    state: present
    name:
    - cmake
    - curl
    - dnsutils
    - ffmpeg
    - git
    - libtool
    - net-tools
    - python3-pip
    - ripgrep
    - rsync
    - the_silver_searcher
    - tcpdump
    - tlp
    - whois

- name: Install applications
  become: yes
  dnf:
    state: present
    name:
    - calibre
    - cheese
    - chromium
    - evince
    - filezilla
    - gimp
    - gnome-boxes
    - gnome-weather
    - htop
    - libreoffice
    - mpv
    - nextcloud-client
    - nmap
    - pass
    - pdfarranger
    - pwgen
    - rclone-browser
    - remmina
    - tmux
    - torbrowser-launcher
    - transmission
    - vim
    - virt-manager
    - vlc
    - wireshark
    - wkhtmltopdf
    - zathura

- name: Install python applications with pip
  pip:
    state: present
    name:
      - youtube-dl

- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  
- name: Install flatpak applications
  community.general.flatpak:
    method: user
    # remote: flathub
    name:
      - com.slack.Slack
      - com.discordapp.Discord
      - com.microsoft.Teams
      - us.zoom.Zoom
      - com.bitwarden.desktop
      - com.visualstudio.code

