---
- name: Add the flathub flatpak repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak applications from Flathub
  community.general.flatpak:
    method: user
    remote: flathub
    name:
      - com.bitwarden.desktop
      - com.discordapp.Discord
      - com.microsoft.Teams
      - com.skype.Client
      - com.slack.Slack
      - com.visualstudio.code
      - us.zoom.Zoom
