---
- name: Install Emacs various packages dependancies
  become: yes
  dnf:
    state: present
    name:
    - clang
    - cmake
    - fd-find
    - git
    - hunspell
    - hunspell-en-US
    - hunspell-fr
    - libtool
    - python3-mutagen
    - ripgrep
    - the_silver_searcher

- name: Install Emacs pdf-tools dependancies
  become: yes
  dnf:
    state: latest
    name:
    - make
    - automake
    - autoconf
    - gcc
    - gcc-c++
    - ImageMagick
    - libpng-devel
    - zlib-devel
    - poppler-glib-devel

- name: Install Emacs
  become: yes
  dnf:
    state: latest
    name:
    - emacs
