---
- name: Add the flathub flatpak repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak applications from Flathub
  community.general.flatpak:
    method: user
    remote: flathub
    name:
      - com.bitwarden.desktop
      - com.dbeaver.DBeaverCommunity
      - com.discordapp.Discord
      - com.microsoft.Teams
      - com.jgraph.drawio.desktop
      - com.skype.Client
      - com.slack.Slack
      - com.spotify.Client
      - com.visualstudio.code
      - org.zotero.Zotero
      - us.zoom.Zoom
