---
# Note: recoll.conf is provided by the dotfiles repo
- name: Install Recoll and suggested packages
  become: yes
  dnf:
    state: latest
    name:
    - recoll
    - antiword
    - catdoc
    - ghostscript
    - perl-Image-ExifTool
    - poppler-utils
    - unrtf

- name: Add Recoll daemon for indexing as autostart script
  copy:
    src: files/recollindex.desktop
    dest: ~/.config/autostart/
    mode: '0640'
