---
- name: Enable the RPM Fusion repositories (free and nonfree)
  become: yes
  dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    disable_gpg_check: yes
    state: present

- name: Install rpm fusion packages
  become: yes
  dnf:
    state: latest
    name:
    - ffmpeg

- name: Install applications (rpm fusion)
  become: yes
  dnf:
    state: latest
    name:
    - mpv
    - vlc
