---
- name: Install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: installed
  with_items: "{{ homebrew_packages }}"
  register: brew

- name: Install homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: installed
  with_items: "{{ homebrew_cask_packages }}"
  register: brewcask

- name: homebrew cleanup
  command: brew cleanup
  when: brewcask.changed
