---
- name: Install homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items: '{{ homebrew_packages }}'

- name: Install homebrew cask packages
  community.general.homebrew_cask:
    name: '{{ item }}'
    state: latest
  with_items: '{{ homebrew_cask_packages }}'
