---
- name: Install Emacs optional dependancies
  homebrew:
    state: latest
    name:
    - coreutils
    - fd
    - hunspell
    - the_silver_searcher

- name: Get dictionaries
  get_url:
    url: "{{ item.url }}"
    dest: "{{ dictionaries_dir }}/{{ item.name }}"
  with_items: "{{ dictionaries }}"

- name: Install Emacs pdf-tools dependancies
  homebrew:
    state: latest
    name:
      - autoconf
      - automake
      - pkg-config
      - poppler

- name: Tap railwaycat Homebrew repository
  community.general.homebrew_tap:
    name: railwaycat/emacsmacport
    state: present

- name: Install Homebrew cask packages
  community.general.homebrew_cask:
    name: emacs-mac
    state: latest
