---
- name: Install Emacs optional dependancies
  homebrew:
    state: latest
    name:
    - coreutils
    - fd
    - ghostscript
    - hunspell
    - the_silver_searcher

- name: Get dictionaries
  get_url:
    url: "{{ item.url }}"
    dest: "{{ dictionaries_dir }}/{{ item.name }}"
  with_items: "{{ dictionaries }}"

- name: Install Emacs pdf-tools dependancies
  homebrew:
    state: latest
    name:
      - autoconf
      - automake
      - pkg-config
      - poppler

- name: Install Emacs Org-roam dependancies
  homebrew:
    state: latest
    name:
      - graphviz

# - name: Tap railwaycat Homebrew repository (emacs-mac)
#   community.general.homebrew_tap:
#     name: railwaycat/emacsmacport
#     state: present

# - name: Install Emacs (emacs-mac)
#   community.general.homebrew_cask:
#     name: emacs-mac
#     state: present

- name: Tap d12frosted Homebrew repository (emacs-plus)
  community.general.homebrew_tap:
    name: d12frosted/emacs-plus
    state: present

- name: Install Emacs (emacs-plus)
  homebrew:
    name: emacs-plus@30
    state: latest

- name: Check if Emacs.app symlink exists
  stat:
    path: /Applications/Emacs.app
  register: emacs_symlink

- name: Symlink emacs-plus to Applications
  command: >
    osascript -e 'tell application "Finder" to make alias file to posix file "/opt/homebrew/opt/emacs-plus@30/Emacs.app" at posix file "/Applications" with properties {name:"Emacs.app"}'
  when: not emacs_symlink.stat.exists
