---
- name: Install NodeJS stack
  homebrew:
    state: latest
    name:
    - node

- name: Create the npm global directory
  file:
    path: ~/.npm-global
    state: directory
  register: nodejsdir

- name: Configure nodejs global prefix
  command: npm config set prefix '~/.npm-global'
  when: nodejsdir.changed

- name: Install npm packages
  npm:
    global: yes
    state: present
    name: "{{ item }}"
  loop:
    - http-server
    - bash-language-server
