---
- name: Clone the Emacs config repo
  git:
    accept_hostkey: yes
    repo: "{{ emacs_repo }}"
    dest: "{{ emacs_dir }}"
    version: master
  register: emacs_pull_result

- name: Make Emacs config
  when: emacs_pull_result.before != emacs_pull_result.after
  make:
    chdir: "{{ emacs_dir }}"
    target: all
