---
- name: Install NodeJS stack (Fedora)
  when: ansible_facts['os_family'] == "Fedora"
  become: yes
  dnf:
    state: latest
    name:
    - nodejs
    - yarnpkg

- name: Install NodeJS stack (MacOS)
  when: ansible_facts['os_family'] == "Darwin"
  homebrew:
    state: latest
    name:
    - node

- name: Create the npm global directory
  file:
    path: ~/.npm-global
    state: directory
  register: nodejsdir

- name: Configure nodejs global prefix
  command: npm config set prefix '~/.npm-global'
  when: nodejsdir.changed

- name: Install npm packages
  npm:
    global: yes
    state: present
    name: "{{ item }}"
  loop:
    - http-server
    - bash-language-server    
